---
- name: Run a command on Windows
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Execute a command using win_command
      win_command: 'curl https://docs.ansible.com/'
      register: command_result

    - name: Display the command result
      debug:
        var: command_result.stdout_lines


